# Generated by Django 5.2.8 on 2025-12-02 10:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_convert_body_to_streamfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("image", 1), ("heading", 2)],
                blank=True,
                use_json_field=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                },
            ),
        ),
    ]

