# Generated by Django 5.2.8 on 2025-12-03 09:04

import json
from django.db import migrations


def convert_richtext_to_streamfield(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")
    for page in HomePage.objects.all():
        if page.body and page.body.strip():
            # Convert RichTextField content to StreamField JSON format
            # Wrap existing rich text in a paragraph block
            stream_data = [{"type": "paragraph", "value": str(page.body)}]
            page.body = json.dumps(stream_data)
        else:
            # Set empty body to empty JSON array
            page.body = json.dumps([])
        page.save(update_fields=['body'])


def convert_streamfield_to_richtext(apps, schema_editor):
    HomePage = apps.get_model("home", "HomePage")
    for page in HomePage.objects.all():
        if page.body:
            try:
                # Extract text from first paragraph block if it exists
                stream_data = json.loads(page.body) if isinstance(page.body, str) else page.body
                if isinstance(stream_data, list) and len(stream_data) > 0:
                    first_block = stream_data[0]
                    if isinstance(first_block, dict) and first_block.get("type") == "paragraph":
                        page.body = first_block.get("value", "")
                    else:
                        page.body = ""
                else:
                    page.body = ""
            except (json.JSONDecodeError, TypeError):
                page.body = ""
            page.save(update_fields=['body'])


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.RunPython(convert_richtext_to_streamfield, convert_streamfield_to_richtext),
    ]

