# Generated by Django 5.2.8 on 2025-12-03 09:04

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_convert_homepage_body_to_streamfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 0),
                    ("paragraph", 1),
                    ("faq", 7),
                    ("testimonials", 15),
                    ("cta", 23),
                ],
                blank=True,
                use_json_field=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "full title"},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Frequently Asked Questions", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "FAQ question", "required": True},
                    ),
                    4: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "FAQ answer", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("question", 3), ("answer", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.ListBlock",
                        (5,),
                        {"help_text": "Add FAQ question/answer pairs"},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("items", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "What our customers say", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Testimonial text", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Person's name", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Role / Company", "required": False},
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 9), ("name", 10), ("role", 11), ("avatar", 12)]],
                        {},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {"min_num": 1}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("testimonials", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Small text above headline", "required": False},
                    ),
                    17: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    18: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Get started", "required": True},
                    ),
                    20: ("wagtail.blocks.URLBlock", (), {"required": True}),
                    21: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    22: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("eyebrow", 16),
                                ("headline", 17),
                                ("body", 18),
                                ("button_text", 19),
                                ("button_url", 20),
                                ("secondary_link_text", 21),
                                ("secondary_link_url", 22),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]

